services:
  - type: web
    name: back_tpi_daw
    env: node
    rootDir: back
    buildCommand: npm ci && npm run build
    startCommand: npm run migration:run:prod && npm run seed && node dist/main
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: 5432
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSL
        value: true
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 8h
      - key: SWAGGER_HABILITADO
        value: false
