events {}

http {
    include /etc/nginx/mime.types;

    # Redirigir HTTP → HTTPS
    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    # HTTPS
    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate     /home/xtsulyts/Escritorio/integrador_des_app_web/deploy/ssl/server.crt;
        ssl_certificate_key /home/xtsulyts/Escritorio/integrador_des_app_web/deploy/ssl/server.key;

        ssl_protocols       TLSv1.2 TLSv1.3;
        ssl_ciphers         HIGH:!aNULL:!MD5;

        # Archivos estáticos Angular
        root /var/www/gestion-proyectos;
        index index.html;

        # SPA — todas las rutas van al index.html
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Proxy al backend NestJS
        location /api/ {
            proxy_pass http://localhost:3000;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
